// SPDX-FileCopyrightText: 2026 Great Honor <randyinthedev@gmail.com>
// SPDX-License-Identifier: Apache-2.0

package inventory

import (
	"encoding/csv"
	"fmt"
	"io"
	"strconv"
	"strings"

	inventoryv1 "github.com/randyinthedev-hash/pqcota-common/gen/pqcota/inventory/v1"
)

// Host — 사용자 관리 hosts 파일의 한 행. **연결 비밀**(SSHUser/SSHKey/SSHPass)은 **런타임 전용**이며
// pqcota 인벤토리에 적재하지 않는다. 적재 대상은 Endpoint()(node_id·name·ip·port)뿐이다.
type Host struct {
	NodeID  string
	Name    string
	IP      string
	Port    int
	SSHUser string
	SSHKey  string // SSH 키 파일 경로 — 비밀, 미영속
	SSHPass string // 암호(권장 안 함) — 비밀, 미영속

	// OS — 이 노드에서 어느 collector를 돌릴지 가른다. 빈 칸은 [OSLinux].
	//
	// **관측하지 않고 받아 적는다.** OS는 collector를 올리기 *전에* 알아야 하는데, 알아내려면
	// 이미 그 노드에 무언가를 올려야 한다 — 닭과 달걀이다. hosts.csv는 사용자의 CMDB이므로
	// 대개 이미 알고 있고, 아는 것을 적는 편이 싸고 확실하다.
	OS string

	// Conn — 어떻게 붙는가. 빈 칸은 [ConnSSH].
	//
	// 여기 적는 이유는 **생성된 인벤토리가 매 실행 덮어써지기 때문이다.** 손으로 더한 연결
	// 설정은 다음 실행에 지워진다 — 접속 방법은 지워지지 않는 곳, 즉 사용자의 CSV에 있어야 한다.
	Conn string
}

// 지원하는 노드 OS. 여기 없는 값은 오타로 보고 거절한다 — 알리지 않고 리눅스로 삼키면
// Windows 노드에 리눅스 collector가 올라가고, 실패는 한참 뒤에 드러난다.
const (
	OSLinux   = "linux"
	OSWindows = "windows"
)

// 지원하는 접속 방법.
const (
	ConnSSH   = "ssh"
	ConnWinRM = "winrm"
)

// 접속 방법별 기본 포트 — CSV에 port를 안 적었을 때만 쓴다.
const (
	portSSH   = 22
	portWinRM = 5985
)

// ParseHosts — 사용자 관리 CSV hosts 파일을 읽는다. 헤더 필수(node_id 필수, 나머지 선택·순서 자유).
// 예 헤더: node_id,name,ip,port,ssh_user,ssh_key,os
// discovery 실행 시마다 사용자가 이 파일을 지정 → pqcota가 읽어 Ansible로 처리한다.
func ParseHosts(r io.Reader) ([]Host, error) {
	cr := csv.NewReader(r)
	cr.TrimLeadingSpace = true
	cr.FieldsPerRecord = -1 // 행별 열 수 가변 허용
	rows, err := cr.ReadAll()
	if err != nil {
		return nil, err
	}
	if len(rows) < 1 {
		return nil, fmt.Errorf("empty file")
	}
	col := map[string]int{}
	for i, h := range rows[0] {
		col[strings.TrimSpace(strings.ToLower(h))] = i
	}
	if _, ok := col["node_id"]; !ok {
		return nil, fmt.Errorf("the header must contain node_id")
	}
	get := func(row []string, name string) string {
		if i, ok := col[name]; ok && i < len(row) {
			return strings.TrimSpace(row[i])
		}
		return ""
	}
	var out []Host
	for _, row := range rows[1:] {
		if len(row) == 0 || strings.HasPrefix(strings.TrimSpace(row[0]), "#") {
			continue
		}
		nid := get(row, "node_id")
		if nid == "" {
			continue
		}
		os := strings.ToLower(get(row, "os"))
		switch os {
		case "":
			os = OSLinux
		case OSLinux, OSWindows:
		default:
			return nil, fmt.Errorf("host %q: os must be %s|%s (got %q)", nid, OSLinux, OSWindows, os)
		}
		conn := strings.ToLower(get(row, "connection"))
		switch conn {
		case "":
			conn = ConnSSH
		case ConnSSH, ConnWinRM:
		default:
			return nil, fmt.Errorf("host %q: connection must be %s|%s (got %q)", nid, ConnSSH, ConnWinRM, conn)
		}
		key := get(row, "ssh_key")
		if conn == ConnWinRM {
			// WinRM은 리눅스 노드로 붙는 길이 아니고, 키로 붙지도 않는다. 알리지 않고 흘려보내면
			// 사용자는 키로 붙는 줄 알고, 실패는 접속 시점에야 난다.
			if os != OSWindows {
				return nil, fmt.Errorf("host %q: connection=%s is for %s nodes (os=%q)", nid, ConnWinRM, OSWindows, os)
			}
			if key != "" {
				return nil, fmt.Errorf("host %q: connection=%s does not use ssh_key — use ssh_pass", nid, ConnWinRM)
			}
		}
		port := portSSH
		if conn == ConnWinRM {
			port = portWinRM
		}
		if p := get(row, "port"); p != "" {
			if v, err := strconv.Atoi(p); err == nil {
				port = v
			}
		}
		out = append(out, Host{
			NodeID: nid, Name: get(row, "name"), IP: get(row, "ip"), Port: port,
			SSHUser: get(row, "ssh_user"), SSHKey: key, SSHPass: get(row, "ssh_pass"),
			OS: os, Conn: conn,
		})
	}
	return out, nil
}

// Endpoint — 인벤토리 적재용 **안전 부분집합**(node_id·name·ip·port). 비밀은 담기지 않는다(타입상 불가).
func (h Host) Endpoint() *inventoryv1.MachineEndpoint {
	return &inventoryv1.MachineEndpoint{NodeId: h.NodeID, Name: h.Name, Ip: h.IP, Port: uint32(h.Port)}
}

// Endpoints — 여러 Host의 안전 부분집합(인벤토리 재사용·표시·수정 대상).
func Endpoints(hosts []Host) []*inventoryv1.MachineEndpoint {
	out := make([]*inventoryv1.MachineEndpoint, 0, len(hosts))
	for _, h := range hosts {
		out = append(out, h.Endpoint())
	}
	return out
}

// RenderAnsibleInventory — hosts에서 **런타임 전용** Ansible 인벤토리(ini)를 생성한다.
// 비밀(user/key/pass)이 여기 실린다 — 이 결과는 실행에만 쓰고 **영속하지 않는다**(pqcota 인벤토리엔 Endpoint만).
//
// OS별 그룹(targets_linux·targets_windows)을 내고 `targets`는 그 둘의 부모로 둔다. `targets`가
// 여전히 전 노드를 가리키므로 **`hosts: targets`로 쓰던 플레이북은 그대로 돈다.** 그룹은
// `--limit`과 group_vars(연결 설정이 갈 자리)를 위해 있다.
func RenderAnsibleInventory(hosts []Host) string {
	byOS := map[string][]Host{}
	for _, h := range hosts {
		os := h.OS
		if os == "" {
			os = OSLinux
		}
		byOS[os] = append(byOS[os], h)
	}

	var b strings.Builder
	b.WriteString("# generated by pqcota (runtime-only, not persisted): discovery targets\n")
	b.WriteString("[targets:children]\n")
	for _, os := range []string{OSLinux, OSWindows} {
		if len(byOS[os]) > 0 {
			fmt.Fprintf(&b, "targets_%s\n", os)
		}
	}
	for _, os := range []string{OSLinux, OSWindows} {
		if len(byOS[os]) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n[targets_%s]\n", os)
		for _, h := range byOS[os] {
			fmt.Fprintf(&b, "%s ansible_host=%s ansible_port=%d", h.NodeID, h.IP, h.Port)
			if h.SSHUser != "" {
				fmt.Fprintf(&b, " ansible_user=%s", h.SSHUser)
			}
			if h.Conn == ConnWinRM {
				b.WriteString(" ansible_connection=winrm")
				if h.SSHPass != "" {
					fmt.Fprintf(&b, " ansible_password=%s", h.SSHPass)
				}
			} else {
				if h.SSHKey != "" {
					fmt.Fprintf(&b, " ansible_ssh_private_key_file=%s", h.SSHKey)
				}
				if h.SSHPass != "" {
					fmt.Fprintf(&b, " ansible_ssh_pass=%s", h.SSHPass)
				}
				// SSH로 Windows에 붙으면 셸이 sh가 아니다. 기본값을 powershell로 두되,
				// sshd의 기본 셸이 cmd면 그쪽으로 바꿔야 한다(아래 주석).
				if os == OSWindows {
					b.WriteString(" ansible_shell_type=powershell")
				}
			}
			b.WriteByte('\n')
		}
	}
	// 접속 방법은 CSV가 정하지만, 그 안에서 사이트마다 다른 값이 둘 남는다. 여기서
	// 지어내면 틀렸을 때 "pqcota가 만든 인벤토리 탓"으로 보이므로 자리만 알려 준다.
	if len(byOS[OSWindows]) > 0 {
		b.WriteString(`
# Two Windows settings vary by site and are not written here. Put them in
# group_vars/targets_windows.yml when the defaults do not fit:
#   over SSH   : ansible_shell_type=cmd     (only if the sshd default shell is cmd, not PowerShell)
#   over WinRM : ansible_winrm_transport=...   (any other ansible_winrm_<option> is passed
#                through to pywinrm, e.g. ansible_winrm_server_cert_validation)
`)
	}
	return b.String()
}
